"""Initial migration.

Revision ID: 1a1b22667497
Revises: 
Create Date: 2025-01-20 12:25:17.432989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a1b22667497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('users')
    op.drop_table('Node')
    op.drop_table('Rosegarden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rosegarden',
    sa.Column('deviceID', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('temperature', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('humidity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('moisture', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deviceID'], ['Node.deviceID'], name='Rosegarden_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Node',
    sa.Column('deviceID', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('temperature', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('humidity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('moisture', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('light', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='Node_ibfk_1'),
    sa.PrimaryKeyConstraint('deviceID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('api_key', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username', 'api_key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
